spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicdb
    username: clinic_user
    password: clinic_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect