spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinicdb
    username: clinic_user
    password: clinic_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

jwt:
  secret: R3R4OVc3clhCZE9yS2pUa0ZtWnQxYmtNdkxRTVVGYk1Ua0N5UGg1c2I4V2F3c2F6Rk1xMGRhZk1YcE51Q1I=
  expiration:
    ms: 3600000
